server:
  port: 8080

spring:
  profiles:
    active: prod
  application:
    name: vben-service
  flyway:
    enabled: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: AUTO
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler

security:
  jwt:
    issuer: vben-service
    access-token-expire-seconds: 1800
    refresh-token-expire-seconds: 1209600
    secret: please-change-to-very-long-key-at-least-256-bits

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
  scalar:
    path: /scalar

system:
  security:
    protected-user-id: 1 # 系统管理员账户
